from pathlib import Path

import pytest

from devctl.generators.docker_scaffold import (
    DockerScaffoldError,
    discover_docker_projects,
    sanitize_service_name,
    scaffold_docker_assets,
)


def write_spring_project(path: Path, name: str = "sample-api") -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "pom.xml").write_text(
        f"""<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>{name}</artifactId>
  <version>0.0.1</version>
  <properties>
    <java.version>21</java.version>
  </properties>
</project>
""",
        encoding="utf-8",
    )
    source_dir = path / "src" / "main" / "java" / "com" / "example"
    source_dir.mkdir(parents=True, exist_ok=True)
    (source_dir / "Application.java").write_text("class Application {}", encoding="utf-8")


def write_angular_project(path: Path, name: str = "sample-front") -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "angular.json").write_text(
        f'{{"projects": {{"{name}": {{"architect": {{"build": {{}}}}}}}}}}',
        encoding="utf-8",
    )
    (path / "package.json").write_text(
        """{
  "name": "sample-front",
  "scripts": {"build": "ng build"},
  "dependencies": {"@angular/core": "^21.0.0"}
}
""",
        encoding="utf-8",
    )
    (path / "src" / "environments").mkdir(parents=True, exist_ok=True)


def write_vue_project(path: Path, name: str = "sample-vue") -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "vite.config.ts").write_text("export default {}", encoding="utf-8")
    (path / "package.json").write_text(
        f'{{"name": "{name}", "scripts": {{"build": "vite build"}}}}',
        encoding="utf-8",
    )


def test_sanitize_service_name():
    assert sanitize_service_name("My API_Service") == "my-api-service"
    assert sanitize_service_name("!!!", fallback="spring") == "spring"


def test_discover_docker_projects_detects_multiple_services(tmp_path):
    write_spring_project(tmp_path / "api")
    write_angular_project(tmp_path / "web")
    write_vue_project(tmp_path / "admin")

    projects = discover_docker_projects(tmp_path)

    assert [project.kind for project in projects] == ["vue", "spring", "angular"]
    assert {project.service_name for project in projects} == {
        "sample-api",
        "sample-front",
        "sample-vue",
    }
    assert next(project for project in projects if project.kind == "spring").java_version == "21"
    assert next(project for project in projects if project.kind == "angular").node_version == "22"


def test_scaffold_docker_assets_dry_run_does_not_write_files(tmp_path):
    write_spring_project(tmp_path / "api")

    result = scaffold_docker_assets(tmp_path, dry_run=True)

    assert result.planned_count > 0
    assert not (tmp_path / "api" / "Dockerfile").exists()


def test_scaffold_docker_assets_generates_only_dockerfiles(tmp_path):
    write_spring_project(tmp_path / "api")
    write_angular_project(tmp_path / "web")

    result = scaffold_docker_assets(tmp_path)

    assert result.created_count == 3
    assert (tmp_path / "api" / "Dockerfile").exists()
    assert (tmp_path / "web" / "Dockerfile").exists()
    assert (tmp_path / "docker-compose-prod.yml").exists()
    assert not (tmp_path / "api" / ".dockerignore").exists()
    assert not (tmp_path / "web" / ".dockerignore").exists()
    assert not (tmp_path / "web" / "nginx.conf").exists()
    assert not (tmp_path / ".env.example").exists()
    assert not (tmp_path / "docker-compose-db.yml").exists()

    spring_dockerfile = (tmp_path / "api" / "Dockerfile").read_text(encoding="utf-8")
    frontend_dockerfile = (tmp_path / "web" / "Dockerfile").read_text(encoding="utf-8")

    assert "FROM maven:3.9-eclipse-temurin-21 AS build" in spring_dockerfile
    assert "USER app" in spring_dockerfile
    assert "FROM node:22-alpine AS build" in frontend_dockerfile
    assert "FROM nginx:1.27-alpine" in frontend_dockerfile


def test_scaffold_docker_assets_skips_existing_files_unless_forced(tmp_path):
    write_spring_project(tmp_path / "api")
    dockerfile = tmp_path / "api" / "Dockerfile"
    dockerfile.write_text("custom", encoding="utf-8")

    result = scaffold_docker_assets(tmp_path)

    assert any(
        operation.path == dockerfile and operation.action == "skipped"
        for operation in result.operations
    )
    assert dockerfile.read_text(encoding="utf-8") == "custom"

    scaffold_docker_assets(tmp_path, force=True)

    assert "Generated by devctl dockerize" in dockerfile.read_text(encoding="utf-8")


def test_scaffold_docker_assets_fails_without_supported_projects(tmp_path):
    with pytest.raises(DockerScaffoldError):
        scaffold_docker_assets(tmp_path)
