spring.application.name=backend-test

spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/backend_test_db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000