"""
Svelte resource scaffolding generator.
Handles the creation of components and routes.
"""

import os

import typer

from devctl.orchestrator.scanner import detect_environment


def generate_svelte_resource(resource_name: str, _fields_str: str, root_path: str = "."):
    """
    Scaffolds a Svelte resource (Route, Component).
    """
    env_state = detect_environment(root_path)

    if not env_state["has_svelte"]:
        typer.secho("❌ Error: No Svelte project detected here.", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    svelte_root = env_state["svelte_path"]
    resource_lower = resource_name.lower()
    entity_name = resource_name.capitalize()

    # Structure: src/routes/resource-name/+page.svelte
    routes_dir = os.path.join(svelte_root, "src", "routes", resource_lower)
    components_dir = os.path.join(svelte_root, "src", "lib", "components")

    os.makedirs(routes_dir, exist_ok=True)
    os.makedirs(components_dir, exist_ok=True)

    typer.secho(f"⚙️  Generating Svelte resource '{entity_name}'...", fg=typer.colors.CYAN)

    # 1. Generate +page.svelte
    page_content = f"""<script lang="ts">
  import {entity_name}List from '$lib/components/{entity_name}List.svelte';
</script>

<h1>{entity_name} Management</h1>

<{entity_name}List />
"""
    with open(os.path.join(routes_dir, "+page.svelte"), "w") as f:
        f.write(page_content)

    # 2. Generate Component
    component_content = f"""<script lang="ts">
  export let items = [];
</script>

<div class="list">
  <h2>{entity_name} List</h2>
  <p>Generated by devctl</p>
  <ul>
    <li>Sample Item</li>
  </ul>
</div>

<style>
  .list {{
    padding: 1rem;
    border: 1px solid #ccc;
  }}
</style>
"""
    with open(os.path.join(components_dir, f"{entity_name}List.svelte"), "w") as f:
        f.write(component_content)

    typer.secho(f"✅ {entity_name} Svelte feature successfully generated!", fg=typer.colors.GREEN)
    typer.echo(f"  - Created: src/routes/{resource_lower}/+page.svelte")
    typer.echo(f"  - Created: src/lib/components/{entity_name}List.svelte")
