"""
NextJS resource scaffolding generator.
Handles the creation of pages and components in the App Router.
"""

import os
import typer
from devctl.orchestrator.scanner import detect_environment


def generate_nextjs_resource(resource_name: str, fields_str: str, root_path: str = "."):
    """
    Scaffolds a NextJS resource (Page, Component).
    """
    env_state = detect_environment(root_path)

    if not env_state["has_nextjs"]:
        typer.secho("❌ Error: No NextJS project detected here.", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    nextjs_root = env_state["nextjs_path"]
    resource_lower = resource_name.lower()
    entity_name = resource_name.capitalize()

    # Structure: src/app/resource-name/page.tsx
    app_dir = os.path.join(nextjs_root, "src", "app", resource_lower)
    components_dir = os.path.join(nextjs_root, "src", "components")
    
    os.makedirs(app_dir, exist_ok=True)
    os.makedirs(components_dir, exist_ok=True)

    typer.secho(f"⚙️  Generating NextJS resource '{entity_name}'...", fg=typer.colors.CYAN)

    # 1. Generate Page (tsx)
    page_content = f"""import React from 'react';
import {{ {entity_name}List }} from '@/components/{entity_name}List';

export default function {entity_name}Page() {{
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold mb-4">{entity_name} Management</h1>
      <{entity_name}List />
    </main>
  );
}}
"""
    with open(os.path.join(app_dir, "page.tsx"), "w") as f:
        f.write(page_content)

    # 2. Generate Component
    component_content = f"""import React from 'react';

export const {entity_name}List: React.FC = () => {{
  return (
    <div className="border p-4 rounded shadow">
      <h2 className="text-xl font-semibold mb-2">{entity_name} List</h2>
      <p>This component was generated by devctl.</p>
      <ul className="list-disc pl-5 mt-4">
        <li>Item 1</li>
        <li>Item 2</li>
      </ul>
    </div>
  );
}};
"""
    with open(os.path.join(components_dir, f"{entity_name}List.tsx"), "w") as f:
        f.write(component_content)

    typer.secho(f"✅ {entity_name} NextJS feature successfully generated!", fg=typer.colors.GREEN)
    typer.echo(f"  - Created: src/app/{resource_lower}/page.tsx")
    typer.echo(f"  - Created: src/components/{entity_name}List.tsx")
