name: Ruff
on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Lint
        run: ruff check .
      - name: Run Ruff Format Check
        run: ruff format --check .
